export const metadata = {
    title: "Authentication practice file",
    description: "Generated by DevTimmy"
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
    }) {
    return (
        <html lang="en">
            <body className="bg-[#f5f5f5] text-green">{children}</body>

        </html>
    )
}